#!/bin/sh
# Copyright (C) 2000-2013 Synology Inc. All rights reserved.

# customized items of package
if [ -z "$SYNOPKG_PKGNAME" ]; then
        # prior DSM 3.2, start script will be run without environment variable
        #  at boot time, thus we need a workaround to gather name and version info
        PACKAGE_NAME="Traefik4srm"
        PACKAGE_VER=`get_key_value "/var/packages/${PACKAGE_NAME}/INFO" "version"`
else
        PACKAGE_NAME=$SYNOPKG_PKGNAME
        PACKAGE_VER=$SYNOPKG_PKGVER
fi

. `dirname $0`/common

if [ "$SYNOPKG_PKG_STATUS" = "INSTALL" ]; then

    TRAEFIK_CONFIG_FILE="traefik4srm.conf"
    TRAEFIK_CONFIG="${SYNOPKG_PKGDEST}/${TRAEFIK_CONFIG_FILE}"
    TRAEFIK_USER="$(echo "${PACKAGE_NAME}" | awk '{print tolower($_)}')"
    LOG="${SYNOPKG_PKGDEST}/${TRAEFIK_USER}.log"

    echo "[$(date +'%T')] #### Start postinst... ####" >>"${LOG}"

    echo "[$(date +'%T')] Linking Traefik binaries" >>"${LOG}"
    DO_LINK

    echo "[$(date +'%T')] Creating Traefik4srm startup config file at \"${TRAEFIK_CONFIG}\"" >>"$LOG"
    touch "${TRAEFIK_CONFIG}"

    # shellcheck disable=SC2154
    {
        echo "[$(date +'%T')] Setting STATIC_CONFIG_FILE=${wizard_static_config_path} in \"${TRAEFIK_CONFIG}\""
    } >>"$LOG"
    {
        echo "STATIC_CONFIG_FILE=${wizard_static_config_path}"
    } >>"${TRAEFIK_CONFIG}"

    echo "[$(date +'%T')] #### Done postinst ####" >>"${LOG}"

fi

exit 0
